name: Publish release
on:
  # Runs whenever a new release is created in GitHub
  release:
    types: [ created ]

jobs:
  # Publish job
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Validate and extract release information
        id: release
        uses: manovotny/github-releases-for-automated-package-publishing-action@f8f252288da9babb174750562ce48fa5e5df70f5 # v2.0.1
      - name: Use Node.js 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          # Never trust the cache for release builds!
          cache: ''
      - run: npm ci
      - name: Publish latest version
        if: steps.release.outputs.tag == ''
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish next version
        if: steps.release.outputs.tag != ''
        run: npm publish --provenance --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
