name: Test on push
on: [push]
jobs:
  test-node:
    name: Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    # Skip job if commit message contains "[skip ci]"
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Check out commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci --workspaces
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run test:types
      - run: npm run test:unit
      - run: npm run test:wpt:node
      - run: npm run test:bundlers

  test-browser:
    name: ${{ matrix.browser }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
        node-version: [ 24 ]
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Check out commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test:wpt:${{ matrix.browser }}
        env:
          HOME: /root

  benchmark:
    name: Benchmark on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Check out commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci --workspaces
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: 'Run benchmark: queue size'
        run: |
          npm run benchmark:queue-size --workspace=test/benchmark-test | tee benchmark-queue-size.txt
      - name: 'Run benchmark: buffered reads'
        run: |
          npm run benchmark:read-buffered --workspace=test/benchmark-test | tee benchmark-read-buffered.txt
      - name: Download previous benchmark data
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: 'Store benchmark result: queue size'
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1
        with:
          name: 'Queue size'
          tool: 'benchmarkjs'
          output-file-path: benchmark-queue-size.txt
          external-data-json-path: ./cache/benchmark-data.json
          auto-push: false
          summary-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Store benchmark result: buffered reads'
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1
        with:
          name: 'Buffered reads'
          tool: 'benchmarkjs'
          output-file-path: benchmark-read-buffered.txt
          external-data-json-path: ./cache/benchmark-data.json
          auto-push: false
          summary-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
