name: Test
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  test-node:
    name: Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    # Skip draft pull requests, and allow pushes to skip CI.
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.draft != true) &&
      (github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - name: Check out commit
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci --workspaces
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run test:types
      - run: npm run test:unit
      - run: npm run test:wpt:node
      - run: npm run test:bundlers

  test-browser:
    name: ${{ matrix.browser }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
        node-version: [ 24 ]
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.draft != true) &&
      (github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - name: Check out commit
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test:wpt:${{ matrix.browser }}
        env:
          HOME: /root

  benchmark:
    name: Benchmark on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.draft != true) &&
      (github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - name: Check out commit
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Use Node.js 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: 26
          cache: npm
      - run: npm ci --workspaces
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Update benchmark baseline to latest polyfill
        run: npm install --workspace test/benchmark-test -D web-streams-polyfill-baseline@npm:web-streams-polyfill@latest
      - name: 'Benchmark: queue size'
        # language=bash
        run: |
          echo "## Queue size" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npm run benchmark:queue-size --workspace=test/benchmark-test | tee --append $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        env:
          BENCH_TTEST: true
          BENCH_REPORTER: text
      - name: 'Benchmark: buffered reads'
        # language=bash
        run: |
          echo "## Buffered reads" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npm run benchmark:read-buffered --workspace=test/benchmark-test | tee --append $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        env:
          BENCH_TTEST: true
          BENCH_REPORTER: text
